---
name: "build-release"

on:
  # Trigger the workflow on push or pull requests, but only for the
  # main branch
  push:
    branches:
    - main

jobs:
  build-release:
    name: "Build Release"
    runs-on: "windows-latest"

    steps:
      # ...
      - name: "Download AutoIT3"
        run: |
          Invoke-WebRequest "https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3.zip" -OutFile autoit-v3.zip
          7z X .\autoit-v3.zip

      - name: "Build, Test"
        run: |
          .\install\Aut2Exe\Aut2exe.exe /in .\windows\5minuser\5minuser.au3 \out .\windows\5minuser\5minuser.exe 
          dir .\windows
          dir .\windows\5minuser\
          .\windows\5minuser\5minuser.exe
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            5minuser.exe
