---
name: "build-release"

on:
  # Trigger the workflow on push or pull requests, but only for the
  # main branch
  push:
    branches:
    - main

jobs:
  build-release:
    name: "Build Release"
    runs-on: "windows-latest"

    steps:
      - name: Checkout sim-user
        uses: actions/checkout@v2
      
      - name: "Download AutoIT3"
        run: |
          Invoke-WebRequest "https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3.zip" -OutFile autoit-v3.zip
          7z X .\autoit-v3.zip

      - name: "Build, Test"
        run: |
          echo $GITHUB_WORKSPACE
          .\install\Aut2Exe\Aut2exe.exe /in $GITHUB_WORKSPACE\windows\5minuser\5minuser.au3 \out $GITHUB_WORKSPACE\windows\5minuser\5minuser.exe 
          dir .\windows
          dir .\windows\5minuser\
          dir $GITHUB_WORKSPACE
          Invoke-Item $GITHUB_WORKSPACE\windows\5minuser\5minuser.exe
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest Auto"
          prerelease: false
          files: |
            $GITHUB_WORKSPACE\windows\5minuser\5minuser.exe
